-- Auto-generated by run.py: register external dependencies before graph import.

INSERT INTO functions (functionid, name, functiontype, description, defaultconfig, modulename, classname, component)
VALUES ('00b2d15a-fda0-4578-b79a-784e4138664b', 'Multi-card Resource Descriptor', 'primarydescriptors', 'Configure the name, description, and map popup of a resource', '{"descriptor_types": {"name": {"nodegroup_id": "", "string_template": ""}, "map_popup": {"nodegroup_id": "", "string_template": ""}, "description": {"nodegroup_id": "", "string_template": ""}}}', 'multicard_resource_descriptor.py', 'MulticardResourceDescriptor', 'views/components/functions/multicard-resource-descriptor')
ON CONFLICT (functionid) DO NOTHING;

INSERT INTO functions (functionid, name, functiontype, description, defaultconfig, modulename, classname, component)
VALUES ('e7d7fd2a-973a-4b2c-8c6e-bd2238d7be70', 'Resource ID Descriptor', 'primarydescriptors', 'Like Multi-card Resource Descriptor but supports <alias|id> and <alias|nodealias> placeholders. <alias|id> expands to the UUID of the first linked resource. <alias|nodealias> expands to the value of that node on the linked resource.', '{"descriptor_types": {"name": {"nodegroup_id": "", "string_template": ""}, "map_popup": {"nodegroup_id": "", "string_template": ""}, "description": {"nodegroup_id": "", "string_template": ""}}}', 'resource_id_descriptor.py', 'ResourceIdDescriptor', 'views/components/functions/multicard-resource-descriptor')
ON CONFLICT (functionid) DO NOTHING;

INSERT INTO report_templates (templateid, name, description, component, componentname, defaultconfig, preload_resource_data)
VALUES ('75e5968a-72cf-4a07-8e0d-1cc3e81d34c8', 'Archive Source Template', 'Archive Source report', 'views/components/reports/archive-source', 'archive-source-report', '{"uncompacted_reporting": true}', false)
ON CONFLICT (templateid) DO NOTHING;
