# Generated by Django 3.2.19 on 2023-07-13 22:08

from django.db import migrations, models
from django.utils.translation import gettext as _


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    def add_functions(apps, schema_editor):
        Function = apps.get_model("models", "Function")

        Function.objects.update_or_create(
            name="BNG Point to GeoJSON",
            functiontype="node",
            modulename="bngpoint_to_geojson_function.py",
            description="Pushes the geometry from a BNG Point node to a related GeoJSON node",
            defaultconfig={"bng_node": "", "geojson_node": "", "bng_nodegroup": "", "geojson_nodegroup": "", "triggering_nodegroups": []},
            classname="BNGPointToGeoJSON",
            component="views/components/functions/bngpoint-to-geojson-function",
            functionid="0434df8d-b98a-4b41-9a0a-68cd9214ad73",
        )

        Function.objects.update_or_create(    
            name="Generate Unique References",
            functiontype="node",
            modulename="generate_unique_references_function.py",
            description="Checks for Simple UID and Resource ID nodes populated and, if not populated, generates them",
            defaultconfig={
                "simpleuid_node": "",
                "resourceid_node": "",
                "uniqueresource_nodegroup": "",
                "triggering_nodegroups": [],
                "nodegroup_nodes": [],
            },
            classname="GenerateUniqueReferences",
            component="views/components/functions/generate-unique-references-function",
            functionid="39d627ae-6973-4ddb-8b62-1f0230e1e3f9",
        )
        
        Function.objects.update_or_create(
            name="GeoJSON to BNG Point",
            functiontype="node",
            modulename="geojson_to_bngpoint_function",
            description="Pushes the geometry from a GeoJSON node's centroid to a related BNG Point node",
            defaultconfig={
                "geojson_input_node": "",
                "bng_output_node": "",
                "geojson_input_nodegroup": "",
                "bng_output_nodegroup": "",
                "triggering_nodegroups": [],
            },
            classname="GeoJSONToBNGPoint",
            component="views/components/functions/geojson-to-bngpoint-function",
            functionid="d9a01773-6092-4cad-b331-ae725ae8fa88",
        )


    def remove_functions(apps, schema_editor):
        Function = apps.get_model("models", "Function")

        for fn in Function.objects.filter(pk__in=[
            "0434df8d-b98a-4b41-9a0a-68cd9214ad73",
            "96efa95a-1e2c-4562-ac1f-b415796f9f75"
            "39d627ae-6973-4ddb-8b62-1f0230e1e3f9",
            "d9a01773-6092-4cad-b331-ae725ae8fa88",
        ]):
            fn.delete()

    operations = [
        migrations.RunPython(add_functions, remove_functions),
    ]
