# Generated by Django 6.0.5 on 2026-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartz', '0002_seed_detsi_api_user_and_oauth_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageitemstate',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('final', 'final'), ('archived', 'archived')], default='draft', max_length=50),
        ),
    ]
