# Generated by Django 5.2.5 on 2025-09-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartz', '0002_datatypes'),
        ('quartz', '0009_add_pottery_object_type'),
    ]

    operations = [
    ]
