# Generated by Django 3.2.19 on 2023-07-13 22:08

from django.db import migrations, models
from django.utils.translation import gettext as _


class Migration(migrations.Migration):

    initial = True
    dependencies = [
            ('quartz', '0010_merge_0002_datatypes_0009_add_pottery_object_type')
    ]

    def add_card_components(apps, schema_editor):
        CardComponent = apps.get_model("models", "CardComponent")

        # Physical Thing IIIF Card
        CardComponent.objects.update_or_create(
            componentid="10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad",
            name=_("Physical Thing IIIF Card"),
            description="",
            component="views/components/cards/physical-thing-iiif-card",
            componentname="physical-thing-iiif-card",
            defaultconfig={"defaultManifest": ""},
        )

    def remove_card_components(apps, schema_editor):
        CardComponent = apps.get_model("models", "CardComponent")

        for card_component in CardComponent.objects.filter(
            pk__in=[
                "10ae2f00-cbda-4a0d-8ca2-5af3b46b37ad",  # Physical Thing IIIF Card
            ]
        ):
            card_component.delete()

    operations = [
        migrations.RunPython(add_card_components, remove_card_components),
    ]
