# Generated by Django 5.2.12 on 2026-03-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quartz", "0012_card_components_afs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CanvasXDigitalResource",
        ),
        migrations.DeleteModel(
            name="ManifestXCanvas",
        ),
        migrations.DeleteModel(
            name="ManifestXDigitalResource",
        ),
        migrations.DeleteModel(
            name="FunctionXGraphProxy",
        ),
        migrations.DeleteModel(
            name="TileModelProxy",
        ),
    ]
